CLASS zcl_wx_oa_fc DEFINITION
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
    " 用于后续优化 替换
    INTERFACES zif_wx_oa_fc .

    DATA control TYPE string.
    DATA id TYPE string .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_WX_OA_FC IMPLEMENTATION.
ENDCLASS.
